# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(889, 667)
        self.horizontalLayoutWidget = QtWidgets.QWidget(main)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 831, 541))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.emailText = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.emailText.setObjectName("emailText")
        self.horizontalLayout.addWidget(self.emailText)
        self.checkResultText = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.checkResultText.setReadOnly(True)
        self.checkResultText.setObjectName("checkResultText")
        self.horizontalLayout.addWidget(self.checkResultText)
        self.checkButton = QtWidgets.QPushButton(main)
        self.checkButton.setGeometry(QtCore.QRect(40, 560, 411, 41))
        self.checkButton.setObjectName("checkButton")
        self.clearButton = QtWidgets.QPushButton(main)
        self.clearButton.setGeometry(QtCore.QRect(460, 560, 411, 41))
        self.clearButton.setObjectName("clearButton")

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Form"))
        self.checkButton.setText(_translate("main", "检查邮件"))
        self.clearButton.setText(_translate("main", "清理检查结果"))
